trustPolicy: no-downgrade

packages:
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
ignoreWorkspaceRootCheck: true
trustPolicyExclude:
  - undici-types@6.20.0
  - '@pnpm/modules-yaml'

catalogs:
  bundling:
    '@rollup/plugin-alias': ^6.0.0
    '@rollup/plugin-commonjs': ^29.0.2
    '@rollup/plugin-node-resolve': ^16.0.3
    '@unocss/nuxt': ^66.6.8
    '@vueuse/nuxt': ^14.3.0
    esbuild: ^0.28.0
    nitropack: ^2.13.4
    nuxt: 4.4.2
    rollup: ^4.60.3
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.6.1
    vite: ^8.0.11
  deps:
    ansis: ^4.2.0
    cac: ^7.0.0
    devframe: ^0.1.22
    fast-npm-meta: ^1.5.1
    get-port-please: ^3.2.0
    h3: ^1.15.11
    js-yaml: ^4.1.1
    launch-editor: ^2.13.2
    ohash: ^2.0.11
    open: ^11.0.0
    p-limit: ^7.3.0
    package-manager-detector: ^1.6.0
    pathe: ^2.0.3
    publint: ^0.3.19
    semver: ^7.7.4
    stream-json: ^2.1.0
    structured-clone-es: ^2.0.0
    tinyexec: ^1.1.2
    tinyglobby: ^0.2.16
    unconfig: ^7.5.0
    unstorage: ^1.17.5
  dev:
    '@antfu/ni': ^30.1.0
    '@nuxt/devtools': ^3.2.4
    bumpp: ^11.1.0
    chokidar: ^5.0.0
    skills-npm: ^1.1.1
    typescript: ^6.0.3
    vite-plugin-inspect: ^11.3.3
    vue-tsc: ^3.2.8
  frontend:
    '@webcontainer/api': ^1.6.4
    '@xterm/addon-fit': ^0.11.0
    '@xterm/xterm': ^6.0.0
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    floating-vue: ^5.2.2
    fuse.js: ^7.3.0
    idb-keyval: ^6.2.2
    modern-screenshot: ^4.7.0
    nanovis: ^1.0.0
    theme-vitesse: ^1.0.0
    vite-hot-client: ^2.2.0
  icons:
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.81
  inlined:
    '@antfu/utils': ^9.3.0
  lint:
    '@antfu/eslint-config': ^8.2.0
    '@nuxt/eslint': ^1.15.2
    '@typescript-eslint/utils': ^8.59.2
    '@unocss/eslint-config': ^66.6.8
    eslint: ^10.3.0
    nano-staged: ^1.0.2
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
  testing:
    '@playwright/test': ^1.59.1
    mlly: ^1.8.2
    type-fest: 4.41.0
    vitest: ^4.1.5
  types:
    '@pnpm/list': ^1000.3.4
    '@pnpm/types': ^1001.3.0
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/js-yaml': ^4.0.9
    '@types/semver': ^7.7.1
    '@types/stream-json': ^1.7.8
    pkg-types: ^2.3.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
